name: Upsert `develop` branch

on:
  push:
    branches: main

jobs:
  upsert-develop-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Rebase `develop` branch to latest `origin/master`
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
      - name: Rebase `develop` branch to latest `origin/main`
        run: |
            git rebase origin/main
            git push -f -u origin develop
